# Generated by Django 4.2.7 on 2024-09-24 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to='myprojects.authors', verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='myprojects.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='myprojects.tag', verbose_name='Keywords'),
        ),
    ]
