# Generated by Django 4.2.7 on 2026-07-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
    ]
