# Generated by Django 4.2.7 on 2025-11-20 00:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='narrative',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
