# Generated by Django 4.2.7 on 2025-11-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='blog.post', verbose_name='Productos relacionados'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
