# Generated by Django 4.2.7 on 2026-07-25 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug_postslughistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postslughistory',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_slug_histories', to='blog.post'),
        ),
    ]
