# Generated by Django 4.2.7 on 2024-09-24 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('comment', models.TextField(max_length=1000)),
                ('hearts', models.PositiveSmallIntegerField(choices=[(1, '💛'), (2, '💛💛'), (3, '💛💛💛'), (4, '💛💛💛💛'), (5, '💛💛💛💛💛')], default=5)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blog.post')),
            ],
        ),
    ]
